create database from_csv_to_database;

create table words
(
    word_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    word varchar(100) unique not null
);

create index ind_word_id on words(word_id);

create table titles
(
    title_id integer generated by default as identity primary key ,
    title varchar(150)
);

create index ind_title_id on titles(title_id);

create table texts
(
    text_id integer generated by default as identity primary key,
    text text,
    title_id integer,
    foreign key (title_id) references titles(title_id)
);

create index ind_text_id on texts(text_id);

select ti.*, t.* from titles ti right join texts t on ti.title_id = t.title_id;

select *
from titles;

select *
    from texts;

drop table titles, texts;

delete from texts;
delete from titles;

select t.title_id, t.title from titles t where t.title='Title 2' ORDER BY t.title_id;
